Last updates haproxy, keepalived pitr, backup, ...

diff --git a/scripts/bin/clustercheck b/scripts/bin/clustercheck
--- a/scripts/bin/clustercheck
+++ b/scripts/bin/clustercheck
@@ -37,9 +37,14 @@ fi
 
 MYSQL_USERNAME="${MYSQL_USERNAME:=-clustercheckuser}"
 MYSQL_PASSWORD="${MYSQL_PASSWORD-clustercheckpassword!}"
-AVAILABLE_WHEN_DONOR=${AVAILABLE_WHEN_DONOR:-0}
 ERR_FILE="${ERR_FILE:-/dev/null}"
-AVAILABLE_WHEN_READONLY=${AVAILABLE_WHEN_READONLY:-1}
+
+# SI ETAT est DONOR 0=> PAS ACCESSIBLE 1=> ACCESSIBLE
+AVAILABLE_WHEN_DONOR=${AVAILABLE_WHEN_DONOR:-0}
+
+# SI 0 et read_only = off => OK SINON FAIL
+AVAILABLE_WHEN_READONLY=${AVAILABLE_WHEN_READONLY:-0}
+
 DEFAULTS_EXTRA_FILE=${DEFAULTS_EXTRA_FILE:-/etc/my.cnf}
 
 #Timeout exists for instances where mysqld may be hung
@@ -96,15 +101,16 @@ then
     echo -en "Percona XtraDB Cluster Node is synced.\r\n"
     sleep 0.1
     exit 0
-else
-    # Percona XtraDB Cluster node local state is not 'Synced' => return HTTP 503
-    # Shell return-code is 1
-    echo -en "HTTP/1.1 503 Service Unavailable\r\n"
-    echo -en "Content-Type: text/plain\r\n"
-    echo -en "Connection: close\r\n"
-    echo -en "Content-Length: 44\r\n"
-    echo -en "\r\n"
-    echo -en "Percona XtraDB Cluster Node is not synced.\r\n"
-    sleep 0.1
-    exit 1
 fi
+
+# Percona XtraDB Cluster node local state is not 'Synced' => return HTTP 503
+# Shell return-code is 1
+echo -en "HTTP/1.1 503 Service Unavailable\r\n"
+echo -en "Content-Type: text/plain\r\n"
+echo -en "Connection: close\r\n"
+echo -en "Content-Length: 44\r\n"
+echo -en "\r\n"
+echo -en "Percona XtraDB Cluster Node is not synced.\r\n"
+sleep 0.1
+exit 1
+
